### ISSUE TITLE
Price oracle could get a stale price

### ISSUE THREAD

**Issue by cvetanovv** [tempusfinance/raft-contracts#296]
## Summary

No check for round completeness could lead to stale prices and wrong price return value, or outdated price. The functions rely on accurate price feed might not work as expected, sometimes can lead to fund loss.

## Vulnerability Detail

The oracle wrapper `_getCurrentChainlinkResponse` call out to an oracle with `latestRoundData()` to get the price of some token. Although the returned timestamp is checked, there is no check for round completeness.

According to Chainlink's [documentation](https://docs.chain.link/data-feeds/price-feeds/historical-data), this function does not error if no answer has been reached but returns 0 or outdated round data. The external Chainlink oracle, which provides index price information to the system, introduces risk inherent to any dependency on third-party data sources. For example, the oracle could fall behind or otherwise fail to be maintained, resulting in outdated data being fed to the index price calculations. Oracle reliance has historically resulted in crippled on-chain systems, and complications that lead to these outcomes can arise from things as simple as network congestion.

## Impact

If there is a problem with chainlink starting a new round and finding consensus on the new value for the oracle (e.g. chainlink nodes abandon the oracle, chain congestion, vulnerability/attacks on the chainlink system) consumers of this contract may continue using outdated stale data (if oracles are unable to submit no new round is started).

This could lead to stale prices and wrong price return value, or outdated price.

As a result, the functions rely on accurate price feed might not work as expected, sometimes can lead to fund loss. The impacts vary and depends on the specific situation like the following:

- incorrect liquidation
- some users could be liquidated when they should not
- no liquidation is performed when there should be
- wrong price feed

## Recommendation

Validate data feed for round completeness:

```solidity
	require(answeredInRound >= roundID, "round not complete");
```

**Comment by StefanVitor** [comment]
This check already exists, but not as a `require` statement, but in function [`_badChainlinkResponse`](https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/Oracles/ChainlinkPriceOracle.sol#L139).
