### ISSUE TITLE
Use of deprecated function for setting token allowances

### ISSUE THREAD

**Issue by Phantasmagoria13** [tempusfinance/raft-contracts#299]
## Title
Use of deprecated function for setting token allowances
## Vulnerability Detail
Throughout the codebase there were multiple locations where the deprecated safeApprove function was used to set allowances:
```
FlashMintLiquidator.sol:45:        collateralToken_.safeApprove(address(amm), type(uint256).max);
OneStepLeverage.sol:45:        collateralToken_.safeApprove(address(amm), type(uint256).max);
OneStepLeverage.sol:46:        collateralToken_.safeApprove(address(positionManager_), type(uint256).max);
```
## Impact
If in any of these locations an allowance is carried over for more than the duration of a transaction, safeApprove may [revert](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.7.3/contracts/token/ERC20/utils/SafeERC20.sol#L54-L56) in subsequent transactions. 
## Recommendation
Consider replacing the instances of safeApprove with the recommended [safeIncreaseAllowance](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.7.3/contracts/token/ERC20/utils/SafeERC20.sol#L61) or [safeDecreaseAllowance](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.7.3/contracts/token/ERC20/utils/SafeERC20.sol#L70) instead.

**Comment by mijovic** [comment]
Linked implementation of OZ's safeApprove states this should be used for initial approval only. This is in the constructor of `FlashMintLiquidator` and `OneStepLeverage` which is actual initial approval for some contracts. Closing as this is not an issue.
