### ISSUE TITLE
[H-01] AMMBase.sol are vulnerable. Attacker can steal assets from contract if they are there.

### ISSUE THREAD

**Issue by dingo2077** [tempusfinance/raft-contracts#309]
# Title
AMMBase.sol are vulnerable. Attacker can steal assets from contract if they are there.

#Impact
All assets which are at contract could be stolen by attacker if attacker input contract address of target asset in `tokenOut`

![image](https://github.com/tempusfinance/raft-contracts/assets/106747559/6552d31d-e437-413b-b877-153bb2b40f3c)

**Comment by rotcivegaf** [comment]
NICE!!!

**Comment by mijovic** [comment]
This contract is not supposed to hold any assets. It is just a helper that is used to swap assets for `FlashMintLiquidator` and `OneStepLeverage` contract.
