### ISSUE TITLE
[H-02] OneInchV5AMM.sol All assets from pool and other pools could be stolen by attacker.

### ISSUE THREAD

**Issue by dingo2077** [tempusfinance/raft-contracts#311]
#TITLE All assets from pool and other pools could be stolen by attacker.
Due to the lack of access control and appropriate calldata checking process there is possibility to stolen all assets depending router interface.

![image](https://github.com/tempusfinance/raft-contracts/assets/106747559/8dc0c7f5-2f3a-4753-a4fa-b615f5231685)
As we see during call `_executeSwap()` there is option to pass custom calldata which are going to router and will be executed there.
Also we see know interface of router but it do not problem to suppose that there are default interface, let's say at Uniswap:
https://docs.uniswap.org/contracts/v2/reference/smart-contracts/router-02
1) function `removeLiquidity()`
2) function `removeLiquidityETH()`
3) Other function like `swap()` 
There is option by attacker to remove liquidity or make arbitrary swap.

- SEVERITY
- High

- A LINK TO THE GITHUB ISSUE
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/AMMs/OneInchV5AMM.sol#L33

-PR (linked to the issue) with at least one test demonstrating the problem and, if possible, a possible fix.

**Comment by mijovic** [comment]
There is no PR linked that shows the issue.
