### ISSUE TITLE
Owner of positions equal or below 100% CR can clawback a portion of their collateral

### ISSUE THREAD

**Issue by rokinot** [tempusfinance/raft-contracts#314]
PR: https://github.com/tempusfinance/raft-contracts/pull/313

## Severity
High

## Description
As described in the [protocol's documentation](https://docs.raft.fi/how-it-works/returning/redistribution#mechanism), in the event a position becomes less than 100% collateralized, it will be eligible for redistribution. The redistributor receives a small fraction of the liquidated position as a high gas fee recompensation, this does, however, allow the mechanism to backfire on the protocol, given the position's owner can also call the function and clawback a percentage of their collateral, on top of still holding their R token balance, deepening the protocol's bad debt. 

Notice that simply impeding the owner from calling the liquidation function (which is where the redistribution mechanism is made avaliable) does not mitigate the issue, as the owner can call this function from a different address. Also notice that such scenario can only happen in a situation where liquidations were not executed in the 110%-100% ICR drop gap, which leaves it safe to assume users/bots/outsiders have not called the liquidation mechanism for some reason, and possibly won't do so for the redistributor, especially given the incentives are even lower than for liquidations.

## Mitigation
Protocol should reconsider the redistribution reward rate mechanic for the redistributor (this will also help cover the protocol as this position will generate bad debt). If the high gas fee for executing such transaction is a problem for the protocol, consider using part of the fee collected on liquidations/redemptions as a cover. Notice R holders are already incentivized to call this function in order to hold the solvency of the protocol by calling this function, given bad debt hurts all of them.

**Comment by mijovic** [comment]
yes, owner can liquidate his own position, I don't see any issue here. This is by design.
