### ISSUE TITLE
Usage of transfer() opcode

### ISSUE THREAD

**Issue by rodiontr** [tempusfinance/raft-contracts#325]
## Summary

Usage of transfer() alone is considered a bug because it uses 2300 gas units. It reverts on failure and the gas will not be refunded to the user.

## Vulnerability Detail

Transfer() opcode is not recommended.

## Impact

Nowadays it's considered as low-risk because of its popularity.

## Code Snippet

https://github.com/tempusfinance/raft-contracts/blob/master/contracts/WstETHWrapper.sol#38
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManagerStETH.sol#51
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManagerStETH.sol#97

## Tool used

Manual Review

## Recommendation

Instead, it's better to use safeTransfer() and safeTransferFrom() as in other contracts of the protocol.

**Comment by StefanVitor** [comment]
In these situations that you sent, it was used familiar tokens (`stETH` here https://github.com/tempusfinance/raft-contracts/blob/master/contracts/WstETHWrapper.sol#38 and `rToken` here https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManagerStETH.sol#51 and here https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManagerStETH.sol#97), so `safeTransfer` and `safeTransferFrom` are not needed.
