### ISSUE TITLE
Users can avoid liquidation by front-running liquidate()

### ISSUE THREAD

**Issue by rodiontr** [tempusfinance/raft-contracts#331]
## Vulnerability Detail

In PositionManager.sol, users can basically avoid liquidation by front-running liquidate() with redeemCollateral() call.

Imagine a following scenario:

1. User1 triggers liquidate() with position's address
2. User2 watches the mempool and sees that his position is about to get liquidated.
3. User2 calls redeemCollateral() and since there are only checks related to the fees, he's able to withdraw all his collateral and front-run liquidator.

Therefore, if the second user's collateral was 150 ETH and he borrowed 100 ETH worth of stablecoin, his ICR initially was 150%. But if his ICR drops below 100% - for example, 90% he now owns more than he provided. And the fact that he can avoid liquidation and redistribution of his collateral across the system, breaks the protocol assumptions and leaves it with 10 ETH worth of stablecoin bad debt.

## Impact

high

## Code Snippet

Liquidate(): https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L189

And redeemCollateral with insufficient checks:

https://github.com/tempusfinance/raft-contracts/blob/master/contracts/PositionManager.sol#L237

## Tool used

Manual Review

## Recommendation

Add some custom checks to make sure that the user cannot avoid liquidation while redeeming the collateral. For example, if ICR <= 100%, revert with cannotRedeemCollateral().

**Comment by mijovic** [comment]
Redemption has nothing to do with user potentially having open position. Liquidation will succeed after redeemCollateral.

**Comment by rodiontr** [comment]
Yes, but if he withdraws all of his collateral and he's under liquidation, it means that there is no more collateral to liquidate

**Comment by rodiontr** [comment]
> Redemption has nothing to do with user potentially having open position. Liquidation will succeed after redeemCollateral.
Yes, but if he withdraws all of his collateral and he's under liquidation, it means that there is no more collateral to liquidate

**Comment by mijovic** [comment]
> > Redemption has nothing to do with user potentially having open position. Liquidation will succeed after redeemCollateral.
> > Yes, but if he withdraws all of his collateral and he's under liquidation, it means that there is no more collateral to liquidate

Collateral is redeemed from every open position equally. Please write a test and you will see you are not right.
