### ISSUE TITLE
User can transfer all the debt from the position to another arbitrary wallet and brick liquidation

### ISSUE THREAD

**Issue by 0xffff11** [tempusfinance/raft-contracts#335]
## TITLE (User can transfer all the debt from the position to another arbitrary wallet and "disable" liquidation)

While creating a position, the position address has to be equal to the msg.sender address or to a delegated address.

Therefore, the position address, it is in fact an active EOA.

An attacker can create a position with his EOA and then transfer all the debt tokens to whatever arbitrary address to avoid liquidations and clear the debt to 0

Essentially while managing a position, debt tokens are minted to the position address:

https://github.com/tempusfinance/raft-contracts/blob/a47d8cb1582f9ef38964d5108ac7160de1d737b1/contracts/PositionManager.sol#L436

which is also the EOA. Once the mint is finished and the debt is accounted, the attacker just transfer the debt tokens to an arbitrary address.

Therefore, in any operation that includes checking the debt, the debt will be essentially 0.  

https://github.com/tempusfinance/raft-contracts/blob/a47d8cb1582f9ef38964d5108ac7160de1d737b1/contracts/PositionManager.sol#L196

Like in this case, the debt for liquidations, will be 0.

## SEVERITY
High, the loss of funds will be massive.

## A LINK TO THE GITHUB ISSUE

https://github.com/tempusfinance/raft-contracts/blob/a47d8cb1582f9ef38964d5108ac7160de1d737b1/contracts/PositionManager.sol#L129

https://github.com/tempusfinance/raft-contracts/blob/a47d8cb1582f9ef38964d5108ac7160de1d737b1/contracts/PositionManager.sol#L436

https://github.com/tempusfinance/raft-contracts/blob/a47d8cb1582f9ef38964d5108ac7160de1d737b1/contracts/PositionManager.sol#L196

## SOLUTION

It depends on the protocol. Having internal accounting instead of checking the balances could work but as it is rebasing would introduce more issues. I think the best is probably not attach positions to addresses, but that is best known by the devs that have a more complex understanding of their idea.

**Comment by mijovic** [comment]
Debt tokens transfers are disabled. Check implementation.

**Comment by 0xffff11** [comment]
Did not find implementation only saw the interface. Can you please point me there? Thanks!

**Comment by mijovic** [comment]
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/ERC20Indexable.sol

You can see in constructor that we assign debt token to new instance of this contract.
