### ISSUE TITLE
There is no validation whether or not `msg.sender == position`, which allow a malicious user to mint `rToken` at no risk by using other user's `position` address

### ISSUE THREAD

**Issue by masaun** [tempusfinance/raft-contracts#337]
## Severity
High

## Description
Within the PositionManager#`managePosition()`, 
- there is the validation to check whether or not the delegatee would be not whitelisted. ([PositionManager.sol#L147-L149](https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L147-L149)) 
- after that, the PositionManager#`_adjustDebt()` would be called. ([PositionManager.sol#L166](https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L166))
```solidity
    function managePosition(
        IERC20 collateralToken,
        address position,  /// @audit
        uint256 collateralChange,
        bool isCollateralIncrease,
        uint256 debtChange,
        bool isDebtIncrease,
        uint256 maxFeePercentage,
        ERC20PermitSignature calldata permitSignature
    )
        external
        override
        collateralTokenExists(collateralToken)
        validMaxFeePercentageWhen(maxFeePercentage, isDebtIncrease)
        onlyDepositedCollateralTokenOrNew(position, collateralToken)
        onlyEnabledCollateralTokenWhen(collateralToken, isDebtIncrease && debtChange > 0)
        returns (uint256 actualCollateralChange, uint256 actualDebtChange)
    {
        if (position != msg.sender && !isDelegateWhitelisted[position][msg.sender]) {  /// @audit
            revert DelegateNotWhitelisted();
        }
        ...

        _adjustDebt(position, debtChange, isDebtIncrease, maxFeePercentage);  /// @audit
        ...
```

Within the PositionManager#`_adjustDebt()`, if `isDebtIncrease = true`,
- the amount (`totalDebtChange`) of `raftDebtToken` would be minted to the `position` address.  ([PositionManager.sol#L432](https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L432)) 
- the amount (`debtChange`) of `rToken` would be minted to the caller address (`msg.sender`). ([PositionManager.sol#L434](https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L434))
```solidity
    /// @dev Adjusts the debt of a given borrower by burning or minting the corresponding amount of R and the Raft
    /// debt token. If the debt is being increased, the borrowing fee is also triggered.
    /// @param position The address of the borrower.
    /// @param debtChange The amount of R to add or remove. Must be positive.
    /// @param isDebtIncrease True if the debt is being increased, false otherwise.
    /// @param maxFeePercentage The maximum fee percentage.
    function _adjustDebt(
        address position,    /// @audit
        uint256 debtChange,
        bool isDebtIncrease,
        uint256 maxFeePercentage
    )
        internal
    {
        ...
        if (isDebtIncrease) {  /// @audit
            uint256 totalDebtChange = debtChange + _triggerBorrowingFee(position, debtChange, maxFeePercentage);
            raftDebtToken.mint(position, totalDebtChange);  /// @audit
            _totalDebt += totalDebtChange;
            rToken.mint(msg.sender, debtChange);  /// @audit
            ...
```

However, there is no input validation to check whether or not the `position` address would be equal to the `msg.sender`.

As a result, if a malicious user (`msg.sender`) can assign other user's (borrower's) address into the `position` parameter when the malicious user call the PositionManager#`managePosition()`.

Then, if the PositionManager#`_adjustDebt()` would be called by the malicious user above with `isDebtIncrease = true` via the PositionManager#`managePosition()`,
- the amount (`totalDebtChange`) of `raftDebtToken` would be minted to the `position` address which is other user's (borrower's) address.
- the amount (`debtChange`) of `rToken` would be minted to the malicious user (`msg.sender`).

This means that the malicious user (`msg.sender`) can mint the amount (`debtChange`) of `rToken` by using other user's `position` address at no risk. On the other hand, that user's `position` address used by the malicious user only receive the amount (`totalDebtChange`) of `raftDebtToken`, meaning that only debt amount of the user's position would be increased despite the user's position does not receive the same amount of rToken.

## Attack scenario
Please see the "Description" above.

## Suggestion
Within the PositionManager#`managePosition()`, consider adding an input validation to check whether or not the `position` address would be equal to the `msg.sender` like this:
```solidity
    function managePosition(
        IERC20 collateralToken,
        address position,  /// @audit info - The address of the borrower
        uint256 collateralChange,
        bool isCollateralIncrease,  /// @audit info - If true, depositing wstETH as a collateral
        uint256 debtChange,
        bool isDebtIncrease,  /// @audit info - If true, borrowing R tokens
        uint256 maxFeePercentage,
        ERC20PermitSignature calldata permitSignature
    )
        external
        override
        collateralTokenExists(collateralToken)
        validMaxFeePercentageWhen(maxFeePercentage, isDebtIncrease)
        onlyDepositedCollateralTokenOrNew(position, collateralToken)
        onlyEnabledCollateralTokenWhen(collateralToken, isDebtIncrease && debtChange > 0)
        returns (uint256 actualCollateralChange, uint256 actualDebtChange)
    {
+       if (position == msg.sender && !isDelegateWhitelisted[position][msg.sender]) {    
+           require(position == msg.sender, "The position address must be msg.sender");
+       else if (position != msg.sender && !isDelegateWhitelisted[position][msg.sender]) {
-       if (position != msg.sender && !isDelegateWhitelisted[position][msg.sender]) {
            revert DelegateNotWhitelisted();
        }
        ...
```

**Comment by mijovic** [comment]
First line of the managePosition function checks if user is whitelisted to manage particular position. There is even a test for this exact scenario you are explaining. 

Not an issue.
