### ISSUE TITLE
FeeCollector.sol declares Ownable2Step but doesn't use its functionality.

### ISSUE THREAD

**Issue by rodiontr** [tempusfinance/raft-contracts#338]
## Vulnerability Detail

The contract uses only one function setFeeRecipient() to transfer ownership but instead it should use one function to transfer ownership and then another to accept ownership from different address:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable2Step.sol#L35
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable2Step.sol#L52

## Code Snippet / Attack Scenario

https://github.com/tempusfinance/raft-contracts/blob/master/contracts/FeeCollector.sol#L4
https://github.com/tempusfinance/raft-contracts/blob/master/contracts/FeeCollector.sol#L25

## Tool used

Manual Review

**Comment by mijovic** [comment]
This doesn't make any sense. Ownable2Step functionality is inherited and works. There is a function that uses onlyOwner and that was the purpose.

Closing an invalid

**Comment by rodiontr** [comment]
> This doesn't make any sense. Ownable2Step functionality is inherited and works. There is a function that uses onlyOwner and that was the purpose.
> 
> Closing an invalid

onlyOwner modifier can be just inherited from Ownable.sol and the purpose of Ownable2Step is to transfer ownership in 2 steps but in the current implementation if you want to set new feeRecipient address, you use just one function without initializing pendingOwner or likewise functionality.
