### ISSUE TITLE
The delegator can always make the delegatee's call fail by front-running and revoking permission.

### ISSUE THREAD

**Issue by innertiaJP** [tempusfinance/raft-contracts#341]
## Summary
The `managePosition` has a delegate function. However, the delegator can revoke the delegation at any time. By front-running and revoking the delegation after confirming the delegatee's attempt to invoke managePosition, the invocation can always fail.
## Vulnerability Detail
The `managePosition` in `PositionManager.sol` has a function to check if it is delegated, and if so, it passes the check.
This delegation can be changed with the `whitelistDelegate` function. However, this function can toggle delegation without restriction.
Thus, a malicious delegator can always cause execution to fail by front-running the `whitelistDelegate` function and denying delegation when delegatee attempts to invoke `managePosition`.
This means that the delegatee will always lose gas money and there is no way to prevent the attack.
In addition, the attack is cheap and easy since all one has to do is invoke the function.
## Impact
Medium severity
The delegatee always loses gas money and trust in the protocol.
## Code Snippet
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L147
https://github.com/tempusfinance/raft-contracts/blob/7c98a5141e308f143a9fc45b4a3c33b43df489fd/contracts/PositionManager.sol#L277-L284
## Tool used

Manual Review

## Recommendation
Add a time lock feature to the delegation.
The delegator will not be able to change the availability of the delegation within that time.

**Comment by mijovic** [comment]
The point of delegation is to give some smart contract allowance to manage your position.
In use cases that we have, this would mean that user would need to frontrun himself?!?

In general use case, giving whitelist to someone and then frontrun that person is not the issue of the trust to the protocol, but more of a trust to that particular user that gave you whitelist and then did frontrun.

Adding timelock can also be dangerous in case you whitelist malicious contract accidentally, then you cannot blacklist it during the timelock.
